- hosts: all
  become: true
    
  # vars_files:
  #   - tf_master.yml

  # vars:
  #   terra_variables: "{{ lookup('file', 'ansible-vars.json') }}"
  #   MOUNT_TARGET: "fs-934fc042.efs.ap-south-1.amazonaws.com"

  tasks:
    - name: update
      command: apt update
      become: yes
      become_method: sudo
      become_user: root

    - name: Install httpd
      command: apt install apache2 -y
      become: yes
      become_method: sudo
      become_user: root

    - name: Start httpd
      command: systemctl start apache2
      become: yes
      become_method: sudo
      become_user: root

    - name: Enable httpd
      command: systemctl enable apache2
      become: yes
      become_method: sudo
      become_user: root

    - name: Install git
      command: apt install git -y
      become: yes
      become_method: sudo
      become_user: root

    - name: Install AWS EFS tools utilities
      command: apt install -y amazon-efs-utils
      become: yes
      become_method: sudo
      become_user: root

    - name: Mounting EFS at /var/www/html
      command: mount -t efs {{ file_sys_id }}:/ /var/www/html
      become: yes
      become_method: sudo
      become_user: root

    - name: Edit fstab so EFS automatically loads on reboot
      command: echo {{ file_sys_id }}:/ /var/www/html efs defaults,_netdev 0 0 >> /etc/fstab
      become: yes
      become_method: sudo
      become_user: root

    - name: Copy the code from github to the /var/www/html
      shell: |
        cd /var/www/html
        git clone https://github.com/cankush625/Web.git